# Change these first
owner: pier4all # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: enablerr preprod
    url: https://preprod.enablerr.dev/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "pier4all Upptime"
  introTitle: "**pier4all Upptime** is the uptime monitor and status page for all sites powered by pier4all."
  introMessage: "View the tickets and statistics for every site and the overall status of pier4all powered sites."
  navbar:
    - title: pier4all
      href: https://wp.enablerr.ch/pier4all/
    - title: enablerr
      href: https://wp.enablerr.ch

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
